### ISSUE TITLE
Code edits for batching

### ISSUE THREAD

**Issue by HeatherWelch** [NOAA-SWFSC-ERD/BREP#3]
change main title to be more specific

FIXED

**Comment by HeatherWelch** [comment]
write out rasters

FIXED

**Comment by HeatherWelch** [comment]
add in zero script

FIXED

**Comment by HeatherWelch** [comment]
turn save (png and raster) into a function

FIXED

**Comment by HeatherWelch** [comment]
write out monthly rds with sightings attached

FIXED

**Comment by HeatherWelch** [comment]
swap the color scale that goes from blue (positive) to white (neutral) to red (negative)

FIXED

**Comment by elhazen** [comment]
AWESOME!

**Comment by HeatherWelch** [comment]
it looks better with a few extra colors...

**Comment by HeatherWelch** [comment]
![sst-09-mean](https://cloud.githubusercontent.com/assets/23531872/26700854/ce7ac67e-46d3-11e7-9310-698317ee16e6.png)

**Comment by HeatherWelch** [comment]
![sst-09-mean](https://cloud.githubusercontent.com/assets/23531872/26700878/e3a64050-46d3-11e7-8db7-a5ba875f5b56.png)

**Comment by HeatherWelch** [comment]
add .75 contour

FIXED

**Comment by HeatherWelch** [comment]
correlate w ENSO index? ask Isaac

FIXED
